chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('room/<int:course_id>/', views.CourseChatRoom.as_view(), name='course_chat_room')
]

educa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from courses import views as course_views

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', course_views.CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/v1/', include('courses.api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from students import views

app_name = 'students'

urlpatterns = [
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<int:pk>/<int:module_id>/', views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
]

chat/models.py
from django.conf import settings
from django.db import models


class ChatGroup(models.Model):
    group_name = models.CharField(max_length=100, unique=True)
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='chats')
    created_at = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    chat_group = models.ForeignKey(ChatGroup, related_name='messages', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def to_json(self):
        return {
            'message_id': self.id,
            'creator': self.creator.email,
            'content': self.content,
            'group_name': self.chat_group,
            'created_at': self.created_at.isoformat()
        }

    def __str__(self):
        return f"{self.creator}"

    class Meta:
        ordering = ('-created_at',)

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.views.generic import View

from chat.models import Message
from courses.models import Course


# Create your views here.
class CourseChatRoom(LoginRequiredMixin, View):
    template_name = 'chat/room.html'

    def get(self, request, *args, **kwargs):
        try:
            course = self.request.user.courses_joined.get(id=kwargs['course_id'])
            chat_room = f"chat_{course.id}"
            # get old messages
            messages = reversed(Message.objects.filter(chat_group__group_name=chat_room)[:20])
            old_messages = []
            for message in messages:
                old_messages.append({
                    'type': 'all_message',
                    'message_id': message.id,
                    'creator': message.creator.email,
                    'content': message.content,
                    'group_name': message.chat_group.id,
                    'created_at': message.created_at
                })
        except Course.DoesNotExist:
            return HttpResponseForbidden()

        return render(self.request, self.template_name, {'course': course, 'old_messages': old_messages})

chat/templates/chat/room.html
{% extends 'base.html' %}
{% load widget_tweaks tz %}

{% block title %}
  Chat Room for {{ course.title }}
{% endblock %}

{% block content %}
  <div>
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title text-secondary text-center mb-3"><a
              href="{% url 'students:student_course_detail' course.id %}"
              class="text-decoration-none link-info">Chat Room {{ course.title }}</a></h3>
          <hr>

          <div class="row">

            <div id="chat" class="mb-3 overflow-auto vh-75"></div>

            {{ old_messages|json_script:"old-messages" }}

          </div>

          <div id="chat-input">

            <div class="row">
              <div class="col-md-10">
                <input type="text" class="form-control" id="chat-message-input" placeholder="Type message">
              </div>
              <div class="col-md-2 d-grid">
                <button class="btn btn-info text-white" id="chat-message-submit">Send</button>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  </div>

  <script>
    const oldMessages = JSON.parse(document.getElementById('old-messages').textContent);

    for (const i in oldMessages) {
        const msg = oldMessages[i];
        const message = msg.content;
        const user = msg.creator;
        const dateOptions = {hour: 'numeric', minute: 'numeric', hour12: true};
        const datetime = new Date(msg['created_at']).toLocaleString('en', dateOptions);
        const isMe = user === '{{request.user}}';

        const name = isMe ? 'Me' : user;

        const msgSourceBG = isMe ? 'chat-bg-me' : 'chat-bg-other';
        const msgAlignSource = isMe ? 'justify-content-end' : '';

        document.getElementById('chat').innerHTML +=
            '<div class="w-100 d-inline-flex mb-2 ' + msgAlignSource + '">' +
            '<div class="w-75 p-2 text-break ' + msgSourceBG + '"><small class="fw-bold">' + name + '<span class="fw-lighter fst-italic"> ' + datetime + '</span></small><br>' + message + '</div>' +
            '</div>';
    };
</script>

{% endblock %}



{% block domready %}
    const url = 'ws://' + window.location.host + '/ws/chat/room/' + '{{ course.id }}/';
    const chatSocket = new ReconnectingWebSocket(url);

    chatSocket.onopen = function (e) {
        console.log('connection ready')
        // chatSocket.send(
        //     JSON.stringify({'type': 'fetch_messages', 'message': 'hello'})
        // )
    };

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        const msgType = data.type;
        const messageObj = data.message

        const $chat = $('#chat');

        for (const i in messageObj) {
            const msg = messageObj[i];
            const message = msg.content;
            const user = msg.creator;
            const dateOptions = {hour: 'numeric', minute: 'numeric', hour12: true};
            const datetime = new Date(msg['created_at']).toLocaleString('en', dateOptions);
            const isMe = user === '{{request.user}}';

            const name = isMe ? 'Me' : user;


            const msgSourceBG = isMe ? 'chat-bg-me' : 'chat-bg-other';
            const msgAlignSource = isMe ? 'justify-content-end' : '';

            $chat.append(
                '<div class="w-100 d-inline-flex mb-2 ' + msgAlignSource + '">' +
                '<div class="w-75 p-2 text-break ' + msgSourceBG + '"><small class="fw-bold">' + name + '<span class="fw-lighter fst-italic"> ' + datetime + '</span></small><br>' + message + '</div>' +
                '</div>'
            );
        }


        $chat.scrollTop($chat[0].scrollHeight);

    };

    chatSocket.onclose = function (e) {
        console.log('Chat socket closed unexpectedly')
    };

    chatSocket.onerror = function (e) {
        console.log(e)
    };

    const $input = $('#chat-message-input');
    const $submit = $('#chat-message-submit');

    $submit.click(function () {
        const message = $input.val();
        if (message) {
            chatSocket.send(JSON.stringify({'type': 'single_message', 'message': message}));
            $input.val('');
            $input.focus();
        }
    });

    $input.focus();
    $input.keyup(function (e) {
        if (e.keyCode === 13) {
            $submit.click()
        }
    });
{% endblock %}