accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    # change password
    path('password-change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('room/<int:course_id>/', views.CourseChatRoom.as_view(), name='course_chat_room')
]

courses/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers

from courses.api import views

schema_view = get_schema_view(
    openapi.Info(
        title="Educa API",
        default_version='v1',
        description="Educa description",
    ),
    public=True,
)

router = routers.DefaultRouter()
router.register('courses', views.CourseViewSet)

app_name = 'courses_api'

urlpatterns = [
    path('subjects/', views.SubjectListView.as_view(), name='subject_list'),
    path('subjects/<int:pk>/', views.SubjectDetailView.as_view(), name='subject_detail'),
    # path('courses/<pk>/enroll/', views.CourseEnrollView.as_view(), name='course_enroll'),
    path('', include(router.urls)),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0))
]

courses/urls.py
from django.urls import path

from courses import views

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<pk>/edit/', views.CourseUpdateMixin.as_view(), name='course_edit'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(),
         name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),

    path('subject/<slug:subject>/', views.CourseListView.as_view(), name='course_list_subject'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
]

educa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from courses import views as course_views

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', course_views.CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/v1/', include('courses.api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from students import views

app_name = 'students'

urlpatterns = [
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<int:pk>/<int:module_id>/', views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
]

courses/forms.py
from django.forms.models import inlineformset_factory
from courses.models import Course, Module
from django.forms.models import inlineformset_factory

from courses.models import Course, Module

ModuleFormset = inlineformset_factory(Course, Module, fields=('title', 'description'), extra=2, can_delete=True)

courses/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework import viewsets
from rest_framework.authentication import BasicAuthentication
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from courses.api.permissions import IsEnrolled
from courses.api.serializers import SubjectSerializer, CourseSerializer, CourseWithContentsSerializer
from courses.models import Course
from courses.models import Subject


class SubjectListView(generics.ListAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer


class SubjectDetailView(generics.RetrieveAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer


# class CourseEnrollView(APIView):
#     authentication_classes = [BasicAuthentication]
#     permission_classes = [IsAuthenticated]
#
#     def post(self, request, pk, format=None):
#         course = get_object_or_404(Course, pk=pk)
#         course.students.add(request.user)
#         return Response({'enrolled': True})


class CourseViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = CourseSerializer
    queryset = Course.objects.all()

    @action(methods=['post'], detail=True, authentication_classes=[BasicAuthentication],
            permission_classes=[IsAuthenticated])
    def enroll(self, request, *args, **kwargs):
        course = self.get_object()
        course.students.add(request.user)
        return Response({'enrolled': True})

    @action(methods=['get'], detail=True, serializer_class=CourseWithContentsSerializer,
            authentication_classes=[BasicAuthentication], permission_classes=[IsAuthenticated, IsEnrolled])
    def contents(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

courses/views.py
import logging

from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django.apps import apps
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.db.models import Count
from django.forms.models import modelform_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from courses.forms import ModuleFormset
from courses.models import Course, Module, Content, Subject
from students.forms import CourseEnrollForm


logger = logging.getLogger(__name__)


class OwnerMixin:
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


class OwnerEditMixin:
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class OwnerCourseMixin(OwnerMixin, LoginRequiredMixin, PermissionRequiredMixin):
    model = Course
    fields = ['subject', 'title', 'slug', 'overview']
    success_url = reverse_lazy('manage_course_list')


class OwnerCourseEditMixin(OwnerCourseMixin, OwnerEditMixin):
    context_object_name = 'course_object'
    template_name = 'courses/manage/course/form.html'


class ManageCourseListView(OwnerCourseMixin, ListView):
    template_name = 'courses/manage/course/list.html'
    permission_required = 'courses.view_course'


class CourseCreateView(OwnerCourseEditMixin, CreateView):
    permission_required = 'courses.add_course'


class CourseUpdateMixin(OwnerCourseEditMixin, UpdateView):
    permission_required = 'courses.change_course'


class CourseDeleteView(OwnerCourseMixin, DeleteView):
    context_object_name = 'course_object'
    template_name = 'courses/manage/course/delete.html'
    permission_required = 'courses.delete_course'


class CourseModuleUpdateView(TemplateResponseMixin, View):
    template_name = 'courses/manage/course/formset.html'
    course = None

    def get_formset(self, data=None):
        return ModuleFormset(instance=self.course, data=data)

    def dispatch(self, request, *args, **kwargs):
        self.course = get_object_or_404(Course, id=kwargs['pk'], owner=request.user)
        return super().dispatch(request, kwargs['pk'])

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response(context={'course': self.course, 'formset': formset}, **kwargs)

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('manage_course_list')
        print('invalid')
        return self.render_to_response(context={'course': self.course, 'formset': formset}, **kwargs)


class ContentCreateUpdateView(TemplateResponseMixin, View):
    template_name = 'courses/manage/content/form.html'
    module = None
    model = None
    content_obj = None

    def get_model(self, model_name):
        if model_name in ['text', 'file', 'image', 'video']:
            return apps.get_model(app_label='courses', model_name=model_name)

        return None

    def get_form(self, model, *args, **kwargs):
        form = modelform_factory(model=model, exclude=['owner', 'order', 'created', 'updated'])
        return form(*args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        self.module = get_object_or_404(Module, id=kwargs['module_id'], course__owner=request.user)
        self.model = self.get_model(kwargs['model_name'])

        if kwargs.get('id'):
            self.content_obj = get_object_or_404(self.model, id=kwargs['id'], owner=request.user)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.get_form(self.model, instance=self.content_obj)
        return self.render_to_response(context={'form': form, 'object': self.content_obj, 'module': self.module})

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.model, instance=self.content_obj, data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()

            if not kwargs.get('id'):
                Content.objects.create(module=self.module, item=obj)
                return redirect('module_content_list', self.module.id)
            else:
                return redirect('module_content_list', self.module.id)


        return self.render_to_response(context={'form': form, 'object': self.content_obj})


class ContentDeleteView(View):
    def post(self, request, id):
        content = get_object_or_404(Content, id=id, module__course__owner=request.user)
        module = content.module

        content.item.delete()
        content.delete()

        return redirect('module_content_list', module.id)


# class ModuleContentListView(TemplateResponseMixin, View):
#     template_name = 'courses/manage/module/content_list.html'
#
#     def get(self, request, module_id):
#         module = get_object_or_404(Module, id=module_id, course__owner=request.user)
#         modules = Module.objects.filter(id=module_id, course__owner=request.user).annotate(
#             total_contents=Count('contents'))
#         return self.render_to_response(context={'module': module, 'modules': modules})


class ModuleContentListView(ListView):
    template_name = 'courses/manage/module/content_list.html'
    context_object_name = 'module'

    def get_queryset(self):
        return get_object_or_404(Module, id=self.kwargs['module_id'], course__owner=self.request.user)


class ModuleOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):

    def post(self, request):
        for module_id, order in self.request_json.items():
            Module.objects.filter(id=module_id, course__owner=request.user).update(order=order)

        return self.render_json_response({'saved': 'OK'})


class ContentOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):

    def post(self, request):
        for content_id, order in self.request_json.items():
            Content.objects.filter(id=content_id, module__course__owner=request.user).update(order=order)

        return self.render_json_response({'saved': 'OK'})


class CourseListView(TemplateResponseMixin, View):
    template_name = 'courses/course/list.html'
    model = Course

    def get(self, request, subject=None):
        subjects = cache.get('all_subjects')
        if not subjects:
            subjects = Subject.objects.annotate(total_courses=Count('courses'))
            cache.set('all_subjects', subjects)
            logger.info('Subjects all_subjects added to cache')

        all_courses = Course.objects.annotate(total_modules=Count('modules'))

        if subject:
            subject = get_object_or_404(Subject, slug=subject)

            key = f"subject_{subject.id}_courses"
            courses = cache.get(key)
            if not courses:
                courses = all_courses.filter(subject=subject).order_by('-created')
                cache.set(key, courses)
                logger.info(f"Filtered courses {key} added to cache")
        else:
            courses = cache.get('all_courses')
            if not courses:
                courses = all_courses
                cache.set('all_courses', courses)
                logger.info("Courses all_courses added to cache")

        return self.render_to_response({'subjects': subjects, 'courses': courses, 'subject': subject})


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/course/detail.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enroll_form'] = CourseEnrollForm(initial={'course': self.object})
        return context

courses/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Educa{% endblock %}</title>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <!-- fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Patua+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet">

  <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.ico' %}"/>
</head>
<body class="bg-light">
<div>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info shadow">
      <div class="container">
        <a class="navbar-brand logo" href="{% url 'course_list' %}">Educa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">


            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'students:student_course_list' %}">Enrolled
                  Courses</a>
              </li>

              {% if request.user.is_instructor %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'course_create' %}">New Course</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'manage_course_list' %}">My Courses</a>
                </li>
              {% endif %}

            {% endif %}

          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="userInfoDropdown" role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                  <i class="bi bi-person-circle"> {{ request.user.email }}</i>

                </a>
                <ul class="dropdown-menu" aria-labelledby="userInfoDropdown">
                  <li class="dropdown-item">{{ request.user.email }}</li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  {% if request.user.is_instructor %}
                    <li><a class="dropdown-item" href="{% url 'course_create' %}">New Course</a></li>
                    <li><a class="dropdown-item" href="{% url 'manage_course_list' %}">My Courses</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                  {% endif %}
                  <li><a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              </li>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>

</div>


<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/reconnecting-websocket.js' %}"></script>

<script>
    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });
</script>
</body>
</html>