chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('room/<int:course_id>/', views.CourseChatRoom.as_view(), name='course_chat_room')
]

educa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from courses import views as course_views

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', course_views.CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/v1/', include('courses.api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from students import views

app_name = 'students'

urlpatterns = [
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<int:pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    path('course/<int:pk>/<int:module_id>/', views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
]

students/forms.py
from django import forms

from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(), widget=forms.HiddenInput)

students/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.core.cache import cache

from courses.models import Course
from students.forms import CourseEnrollForm
import logging

logger = logging.getLogger(__name__)


# Create your views here.
class StudentRegistrationView(CreateView):
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('students:student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data

        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        logger.info(f"Student {self.request.user.email} enrolled in {self.course}")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('students:student_course_detail', args=[self.course.id])
        # return reverse_lazy('course_list')


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/course/list.html'
    context_object_name = 'courses'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'students/course/detail.html'
    context_object_name = 'course'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        course = self.get_object()

        if 'module_id' in self.kwargs:
            key = f"enrolled_module_{course.id}_{self.kwargs['module_id']}"
            module = cache.get(key)
            if not module:
                module = course.modules.get(id=self.kwargs['module_id'])
                cache.set(key, module)
                logger.debug(f"Added course module {key} to cache")
            context['module'] = module
        else:
            context['module'] = course.modules.all()[0]

        return context

students/templates/students/course/detail.html
{% extends 'base.html' %}
{% load cache %}
{% load widget_tweaks %}

{% block title %}
  {{ course.title }}
{% endblock %}

{% block content %}
  <!-- heading -->
  <div class="row">
  <h1 class="text-secondary text-center">{{ course.title }}</h1>
  </div>

  <div class="row">
    <!-- sidebar -->
    <div class="col-md-3">
      <div class="list-group">
        {% for m in course.modules.all %}
          <a href="{% url 'students:student_course_detail_module' course.id m.id %}"
             class="list-group-item list-group-item-action {% if m.id == module.id %}list-group-item-info{% endif %}">
            Module {{ m.order|add:1 }}
            <br>
            <em>{{ m.title }}</em>
          </a>
        {% empty %}
          No modules yet
        {% endfor %}

        <a href="{% url 'chat:course_chat_room' course.id %}"
             class="list-group-item list-group-item-action list-group-item-warning">
            Course chat room

          </a>
      </div>
    </div>

    <!-- main content -->
    <div class="col-md-9">
{#    {% cache 60 modules_content module %}#}
      {% for content in module.contents.all %}
        {% with item=content.item %}
          <h2 class="text-secondary">{{ item.title }}</h2>
          {{ item.render }}
        {% endwith %}
      {% endfor %}
{#    {% endcache %}#}

    </div>

  </div>

{% endblock %}

students/templates/students/course/list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  ({{ courses.count }}) Enrolled Courses
{% endblock %}

{% block content %}
  <div class="row col-md-8 offset-md-2 mb-3">
    <h1 class="text-secondary text-center">Enrolled Courses</h1>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      {% for course in courses %}

        <div class="card mb-1">
          <div class="card-body">
            <h2 class="card-title text-center text-secondary">{{ course.title }}</h2>
            <p class="text-center"><a href="{% url 'students:student_course_detail' course.id %}"
                                      class="link-info text-decoration-none">Access Contents</a></p>
          </div>
        </div>

      {% empty %}
        <p>You are not enrolled in any course</p>
      {% endfor %}

    </div>
    <div class="col-md-2"></div>

  </div>

{% endblock %}